#!/usr/bin/env python3
"""Amend the authoritative W1 register with the Congrong Lu reinstatement (task 043, 2026-09-20).

The corpus gained one document on 2026-09-20: `data/corpus/congronglu.json`, rebuilt from scratch out
of the pinned CBETA XML P5 witness `T48n2004` (100 cases; 601 fields measured, 601 EXACT, 0 flagged).
The authoritative W1 register has to record it. This script produces the dated overlay that does so,
with the smallest possible change:

* **35 document entries are inherited verbatim** from the 2026-09-10 overlay. The corpus has been
  re-keyed since that run (five Wave-1 PRs, plus the RE-KEY campaign), so a fresh full-corpus
  collation today would move several documents' *measured* classes — a re-designation of the
  evidence, which the standing rulings forbid. Inheritance, not re-measurement, is what keeps the
  designated figures (630 flagged) exactly where the owner pinned them.
* **One document entry is appended**, copied verbatim from the harness's own measurement of that
  document (`scripts/collate_corpus.py --doc congronglu --compare-historical-refs … --new-document
  congronglu`), whose run is committed as `sessions/COLLATION_REGISTER_2026-09-20_CONGONGLU_MEASUREMENT.json`.
* **The register-level blocks are recomputed** with the harness's own code — `collate_corpus.reproduce`
  for the reproduction block and `source_review` for the class/status arithmetic — never transcribed.

The declared exception: `congronglu`'s reference `T48n2004` has **no reproducible 2026-09-09 anchor**
(the historical manifest's line for that work cannot be regenerated by the committed rule from any
CBETA revision tested), so the register records `historical_status = 'drift'` for it, lists the
document under `documents_with_drifted_references`, and declares the document in
`generation_parameters.new_documents`. That declaration is what tells the validators this drift is a
recorded fact about a pre-rule artifact rather than a failed collation: the document did not exist in
the 2026-09-09 evidence pass, its pinned anchor verifies byte-identically, and its collation is
500/500 content fields EXACT. Every document the historical register *does* cover keeps the strict
rule — a drifted or unlisted reference never upgrades a W1 status. See
`sessions/COLLATION_W1_2026-09-20_CORRECTION.md` §4 for the full adjudication.

Inputs (all committed):
* `sessions/COLLATION_REGISTER_2026-09-10_CORRECTION.json` — the 35 inherited entries;
* `sessions/COLLATION_REGISTER_2026-09-20_CONGONGLU_MEASUREMENT.json` — the new document as measured;
* `sessions/COLLATION_REGISTER_2026-09-09.json` — the historical register the overlay corrects;
* `sessions/COLLATION_W1_2026-09-20_refs_manifest.txt` (40 works) and
  `sessions/COLLATION_W1_2026-09-09_refs_manifest.txt` (the 187-work historical anchor).

Output: `sessions/COLLATION_REGISTER_2026-09-20_CORRECTION.json` (deterministic byte-for-byte).

Usage:
    python3 scripts/record_congronglu_evidence.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import collate_corpus  # noqa: E402 - the harness's own reproduction builder
import collate_refs  # noqa: E402
import source_review  # noqa: E402
import w1_evidence  # noqa: E402

PREVIOUS_REGISTER = ROOT / "sessions/COLLATION_REGISTER_2026-09-10_CORRECTION.json"
HISTORICAL_REGISTER = ROOT / "sessions/COLLATION_REGISTER_2026-09-09.json"
MEASUREMENT = ROOT / "sessions/COLLATION_REGISTER_2026-09-20_CONGONGLU_MEASUREMENT.json"
OUTPUT = ROOT / "sessions/COLLATION_REGISTER_2026-09-20_CORRECTION.json"

NEW_KEY = "congronglu"
GENERATED = "2026-09-20"
#: The figure the 2026-09-09 human-readable report claimed; its register sums to 622, so the claim
#: stays recorded as superseded (the 2026-09-10 overlay already recorded it that way).
HISTORICAL_REPORT_FLAGGED = 637
#: The designated flagged total this overlay must not move: the new document contributes no flags.
DESIGNATED_FLAGGED_TOTAL = 630

NOTES = [
    "2026-09-20 (task 043, owner-ruled evidence-model extension): data/corpus/congronglu.json enters "
    "the active manifest as the 36th document, extracted from scratch out of the pinned CBETA XML P5 "
    "witness T48n2004 (upstream dbdea41071e1e260ad84b72faefd4587333cf76d; reference digest "
    "70413b279195b74148f03d6081c311511393dfaa65458f73e107116510738ba0, 88,155 CJK), after the seed "
    "was quarantined on 2026-08-10 for generated placeholders and wrong case-number/page claims. Its "
    "collation is 100/100 cases and 500/500 source-content fields EXACT with 0 flagged, measured by "
    "scripts/collate_corpus.py --doc congronglu (recorded in "
    "sessions/COLLATION_REGISTER_2026-09-20_CONGONGLU_MEASUREMENT.json). The 35 per-document entries "
    "this overlay inherits are the 2026-09-10 record's entries verbatim: the corpus has been re-keyed "
    "since that run, so re-measuring them here would move their measured classes, which the standing "
    "rulings forbid. The designated flagged total therefore stays 630 — the new document adds none — "
    "while today's data measures 486 flagged fields over the same fields.",
    "The new document's reference has no historical anchor, and that is declared rather than implied: "
    "the 2026-09-09 anchor manifest lists a T48n2004 line whose digest "
    "(06d8ef7f44a1c51cef7af5ea9b98539cf23050b1e91b594947eab4226ee736e8) the committed rule does not "
    "reproduce from any CBETA revision tested, so the entry records historical_status='drift' and the "
    "document is listed under documents_with_drifted_references. Because the 2026-09-09 pass predates "
    "this document's evidence record, that drift is a recorded fact rather than a veto here — the "
    "collated claim rests on the authoritative manifest, where T48n2004 verifies byte-identically. The "
    "waiver is declared in generation_parameters.new_documents and enforced in scripts/w1_evidence.py "
    "and scripts/collate_corpus.py (--new-document); every document the historical register covers "
    "keeps the strict both-anchor rule, so 'a drifted or unlisted reference never upgrades a W1 status' "
    "still holds where it was written to hold. The full adjudication, including the two other candidate "
    "readings of that line, is sessions/COLLATION_W1_2026-09-20_CORRECTION.md §4.",
]


def load(path: Path) -> dict:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def witness_note() -> str:
    return (
        "Reinstated 2026-09-20 from the pinned witness: all 500 source-content fields (100 cases × "
        "pointer 垂示, 本則, 評唱, 頌 and post-verse 評唱) are verbatim and contiguous in T48n2004, 0 "
        "fields flagged. Case locators anchor at the lb line head printed before each case div, which "
        "reproduces the five anchors the 2026-08-10 containment table recorded (cases 33/34/35/37/38). "
        "This document is new to the evidence: the 2026-09-09 pass never covered it, so its reference "
        "has no historical anchor — the entry records that drift (historical_status='drift') and the "
        "document is declared in generation_parameters.new_documents. No quarantined Congronglu record "
        "was read or copied: the producer's only input is the pinned witness file, and every field is "
        "asserted to be a contiguous run of that extraction."
    )


def main() -> int:
    previous = load(PREVIOUS_REGISTER)
    historical = load(HISTORICAL_REGISTER)["documents"]
    measurement = load(MEASUREMENT)
    current_digests = collate_refs.read_digest_manifest(
        str(ROOT / w1_evidence.FIXED_METADATA["correction_refs_manifest_path"]))
    historical_digests = collate_refs.read_digest_manifest(str(ROOT / w1_evidence.HISTORICAL_REFS_MANIFEST))

    documents = dict(previous["documents"])
    if NEW_KEY in documents:
        raise SystemExit(f"{NEW_KEY} is already recorded in {PREVIOUS_REGISTER.name}; this overlay adds it")
    measured = measurement["documents"].get(NEW_KEY)
    if not isinstance(measured, dict):
        raise SystemExit(f"{MEASUREMENT.name} carries no {NEW_KEY} entry to record")
    if measured.get("source_review_status") != source_review.COLLATED_STATUS:
        raise SystemExit(f"{NEW_KEY} measures {measured.get('source_review_status')!r}, not a collated "
                         "document; the overlay would be recording a failed collation, not a reinstatement")
    entry = dict(measured)
    entry["witness_note"] = witness_note()
    documents[NEW_KEY] = entry

    # Register-level reference verification: every work the entries claim (plus every work the
    # authoritative manifest lists — the two sets must be identical) with its status against both
    # anchors.
    claimed = set(previous["reference_verification"]["refs"]) | set(entry.get("reference_verification") or {})
    if claimed != set(current_digests):
        raise SystemExit("the entries' reference set does not match the authoritative digest manifest: "
                         f"missing={sorted(set(current_digests) - claimed)} extra={sorted(claimed - set(current_digests))}")
    register_details = {}
    for work in sorted(claimed):
        digest = current_digests[work]
        historical_digest = historical_digests.get(work)
        register_details[work] = {
            "sha256": digest,
            "manifest": w1_evidence.FIXED_METADATA["correction_refs_manifest_path"],
            "status": "verified",
            "historical_manifest": w1_evidence.HISTORICAL_REFS_MANIFEST,
            "historical_status": ("unlisted" if historical_digest is None
                                  else "verified" if historical_digest == digest else "drift"),
        }

    drifted_docs = sorted(
        key for key, doc in documents.items()
        if doc.get("refs_total", 0) > doc.get("refs_verified", 0)
        or doc.get("refs_verified", 0) > doc.get("refs_historically_verified", 0)
    )
    register = {
        "kind": "w1-correction",
        "generated": GENERATED,
        "harness": "scripts/collate_corpus.py",
        "corrects": previous["corrects"],
        "reference_extraction": previous["reference_extraction"],
        "upstream": previous["upstream"],
        "refs_manifest": w1_evidence.FIXED_METADATA["correction_refs_manifest_path"],
        "historical_refs_manifest": w1_evidence.HISTORICAL_REFS_MANIFEST,
        "generation_parameters": {
            "kind": "w1-correction",
            "generated": GENERATED,
            "corrects": previous["corrects"],
            "refs_manifest": w1_evidence.FIXED_METADATA["correction_refs_manifest_path"],
            "compare_historical_refs": w1_evidence.HISTORICAL_REFS_MANIFEST,
            "compare_register": previous["corrects"],
            "historical_report_flagged": HISTORICAL_REPORT_FLAGGED,
            "upstream_repo": collate_refs.UPSTREAM_REPO,
            "upstream_revision": w1_evidence.PINNED_UPSTREAM_REVISION,
            "require_verified_refs": True,
            "refs_dir_provided": True,
            "new_documents": [NEW_KEY],
            "note": NOTES,
        },
        "content_denominator": previous["content_denominator"],
        "status_scope": source_review.STATUS_SCOPE,
        "documents": documents,
        "reference_verification": {
            "manifest": w1_evidence.FIXED_METADATA["correction_refs_manifest_path"],
            "historical_manifest": w1_evidence.HISTORICAL_REFS_MANIFEST,
            "rule": "statuses are byte-identity of the reference file against a named digest "
                    "manifest; `drift` never rescues a claim and never upgrades one",
            "counts": {state: sum(1 for d in register_details.values() if d["status"] == state)
                       for state in ("verified", "drift", "unlisted", "none")},
            "historical_counts": {state: sum(1 for d in register_details.values()
                                             if d["historical_status"] == state)
                                  for state in ("verified", "drift", "unlisted", "none")},
            "drifted_refs": sorted(work for work, d in register_details.items()
                                   if "drift" in (d["status"], d["historical_status"])),
            "refs": register_details,
        },
        "aggregate": {
            "documents": len(documents),
            "flagged_entries": source_review.flagged_total(documents),
            "fields_total": sum(d["fields_total"] for d in documents.values()),
            "content_fields_total": sum(d["content_fields_total"] for d in documents.values()),
            "content_fields_collated": sum(d["content_fields_collated"] for d in documents.values()),
            "metadata_fields_total": sum(d["metadata_fields_total"] for d in documents.values()),
            "class_totals": source_review.summary_flags(documents),
            "source_review_status_counts": source_review.status_counts(
                source_review.derive_status(d) for d in documents.values()),
            "documents_without_evidence": sorted(set(collate_corpus.DOCS) - set(documents)),
            "documents_with_drifted_references": drifted_docs,
        },
    }
    register["reproduction"] = collate_corpus.reproduce(
        documents, str(HISTORICAL_REGISTER), HISTORICAL_REPORT_FLAGGED, NOTES)

    if register["aggregate"]["flagged_entries"] != DESIGNATED_FLAGGED_TOTAL:
        raise SystemExit(f"the overlay moves the designated flagged total to "
                         f"{register['aggregate']['flagged_entries']}; it must stay at "
                         f"{DESIGNATED_FLAGGED_TOTAL} (the new document contributes no flags)")
    OUTPUT.write_text(json.dumps(register, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"register written: {OUTPUT.relative_to(ROOT)}")
    print(f"aggregate: {json.dumps(register['aggregate'], ensure_ascii=False)}")
    print(f"reference_verification: {json.dumps(register['reference_verification']['counts'])} "
          f"historical {json.dumps(register['reference_verification']['historical_counts'])}")
    print(f"reproduction: compared={register['reproduction']['documents_compared']} "
          f"identical={register['reproduction']['documents_classification_identical']} "
          f"changed_status={register['reproduction']['documents_with_changed_status']} "
          f"flagged={register['reproduction']['flagged_entries']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
